amp-labs/docs

src/provider-guides/atlassian.mdx

I don't mention any doc references.
But in case we want to add endpoints and operations for issues:
* [Read Issue](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-search-get)
* [Create Issue](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post)
* [Update Issue](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-put)

Supported objects: Atlassian

---

src/generate-mint.ts
src/mint.json

Mintlify lets us collect +1/-1 on docs as feedback (https://mintlify.com/blog/launch-week-day-2). It also lets users suggest edits. We'll have to add branch protection before we merge this PR in.

chore: Enable feedback on docs

---

src/embeddable-ui-components.mdx

adds uninstallSuccess to docs.
- update embeddable-ui-components.mdx

[ENG-1534] docs: add uninstall success docs

---

src/api.json
src/cli/command-reference.mdx
src/cli/overview.mdx
src/cli/reference.mdx
src/generate-mint.ts
src/mint.json

- Updated CLI overview section
- Added Commands reference section

Commands Documentation

---

src/define-integrations/read-actions.mdx
src/destinations.mdx
src/quickstart.mdx

feat: Add section to destinations on payload size and add backfill to examples

---

src/embeddable-ui-components.mdx

[coordinated merge]
updates docs to support v2 of @amp-labs/react 
- removes chakra peer deps as requirement
- adds updated examples

docs: update embeddable-ui-components v2

---

src/embeddable-ui-components.mdx

Revert "Update params list for ConnectProvider"

---

src/destinations/webhooks.mdx

Add `installationUpdateTime` to the webhook example

[ENG-1713] feat: Add installationUpdateTime to example

---

src/provider-guides/pipedrive.mdx

- Removed the scope step as it's no longer valid.
- Added the supported objects in Read/Write
The samples [PR](https://github.com/amp-labs/samples/pull/4)

[CON-701] feat: add supported objects Pipedrive

---

src/generate-mint.ts
src/mint.json
src/provider-guides/lemlist.mdx

Added a line specific for this: [comment](https://linear.app/ampersand/issue/CON-597/lemlist-proxy#comment-2c1fc372)

[CON-604] feat: Add Lemlist guides

---

src/embeddable-ui-components.mdx

adds faq section for embeddable ui components

[ENG-1721] docs: add migration v2 embeddable ui components faq

---

src/provider-guides/zoho.mdx

Revert "Revert "[CON-703] feat: Add Documentation for ZohoCRM supported objects""

---

src/provider-guides/constantContact.mdx

Added supported objects, there are some more pending PRs before this can be merged.

[CON-704] ConstantContact: supported objects

---

src/overview.mdx
src/provider-guides/apollo.mdx
src/provider-guides/atlassian.mdx
src/provider-guides/attio.mdx
src/provider-guides/close.mdx
src/provider-guides/constantContact.mdx
src/provider-guides/customerJourneysApp.mdx
src/provider-guides/instantly.mdx
src/provider-guides/kit.mdx
src/provider-guides/klaviyo.mdx
src/provider-guides/marketo.mdx
src/provider-guides/outreach.mdx
src/provider-guides/pipedrive.mdx
src/quickstart.mdx

Ran the files in a typo checker.

fix: generic typos

---

src/define-integrations/write-actions.mdx

[ENG-1814] docs: add `associations` to write actions

---

src/api.json
src/define-integrations/subscribe-actions.mdx
src/destinations/webhooks.mdx
src/generate-mint.ts
src/mint.json
src/provider-guides/hubspot.mdx

- Added details about the hubspot private preview.

[ENG-2007] - Subscribe actions for HubSpot private preview

---

src/mint.json
src/provider-guides/marketo.mdx

Update Marketo guide

---

src/define-integrations/subscribe-actions.mdx

- Revised updateEvent documentation to include use of `requiredWatchFields`

RequiredWatchFields

---

src/generate-mint.ts
src/mint.json
src/provider-guides/hunter.mdx

This PR adds the Provider guide for the Hunter Proxy connector.

feat (Hunter) : add provider guide

---

src/generate-mint.ts
src/mint.json
src/provider-guides/goTo.mdx

chore: Renamed GoToWebinar connector name to GoTo

---

src/provider-guides/monday.mdx

Updates the docs for monday.com 

[CON-966] docs: update docs for monday.com for read & write

---

src/use-with-ai-ide.mdx

chore: remove local setup section for mcp server

---

src/destinations/webhooks.mdx
src/subscribe-actions.mdx

- Updates `amp.yaml` and webhook message delivered for Salesforce subscribe action

Modified example yaml and webhook messages for salesforce

---

src/provider-guides/ashby.mdx

This PR adds guides for Ashby deep connector and its supported objects.

[CON-1600] feat (Ashby): add supported object and action

---

src/provider-guides/marketo.mdx

Adds the activities object read & write support. Updated the objects naming to lowercase.

feat: Update marketo object supports

---

src/generate-mint.ts
src/mint.json

fix productboard guide

---

src/docs.json

Ran `mint upgrade`. Mintlify had a breaking change in the way they generated docs. 

fix: mint upgrade should fix the docs

---

package.json
pnpm-lock.yaml

chore: update dev deps

---

src/docs.json

fix: add .json suffix

---

src/mcp.mdx

chore: add syntax highlighting to mcp docs

---

src/ai-sdk.mdx

chore: update toolnames for aisdk

---

src/ai-sdk.mdx
src/docs.json
src/generate-docs.ts
src/mcp.mdx

launch: release docs for AI SDK and MCP server

---

src/provider-guides/hubspot.mdx
src/provider-guides/salesforce.mdx

chore: revise "Using a connector" section to mention subscribe

---

src/docs.json
src/generate-docs.ts
src/provider-guides/domo.mdx

This PR add provider guides for Domo

feat: add Domo provider guide

---

src/provider-guides/clariCopilot.mdx

This PR updated Read action guides and add guides for Write action.

 Clari Copilot: update Read action guide + add write action guide 

---

src/provider-guides/atlassian.mdx

Fix bad links in Atlassian guide

---

src/docs.json
src/generate-docs.ts
src/provider-guides/freshchat.mdx

This PR add provider guide for Freshchat proxy connector

[CON-738] feat: add Freshchat provider guide 

---

src/docs.json
src/generate-docs.ts
src/provider-guides/flatfile.mdx

This PR adds provider guide for Flatfile Proxy connector.

[CON-1827] feat: add Flatfile provider guide

---

src/docs.json
src/generate-docs.ts
src/provider-guides/jobber.mdx

This PR adds Jobber connector proxy guide

[CON-1744] feat: add Jobber provider guide

---

src/provider-guides/netsuite.mdx

chore: add netsuite proxy

---

src/provider-guides/dixa.mdx

Adds Dixa connector supported objects

[CON-1100] feat: Add Dixa connector supported objects docs

---

src/provider-guides/chilipiper.mdx

Adds Chilipiper connector supported objects

[CON-994] feat: Add Chilipiper connector supported objects

---

src/provider-guides/lever.mdx

[CON-1998] feat: Extended the lever provider guides

---

src/provider-guides/google.mdx

Add link to calendar example

---

src/provider-guides/fireflies.mdx

https://github.com/amp-labs/connectors/pull/1912

chore: update fireflies base URL 

---

src/docs.json
src/generate-docs.ts
src/platform.json
src/provider-guides/netsuite.mdx
src/reference/installation/list-installations-for-a-project.mdx
src/reference/platform.json

[ENG-2378] feat: add netsuite docs

---

src/provider-guides/campaignMonitor.mdx

[CON-1378] feat: [Campaign Monitor] Extended the provider guides

---

src/provider-guides/capsule.mdx

[CON-1330] feat(capsule): Supported Objects

---

src/provider-guides/dynamicsBusinessCentral.mdx

[CON-1314] feat(dynamicsBusinessCetnral): Read & Write

---

src/docs.json
src/generate-docs.ts
src/provider-guides/aws.mdx

Outlined layout for the AWS guide and listed the supported operations.

[CON-1667] feat: AWS provider guide

---

src/write-actions.mdx

[ENG-2482] chore: write mode docs

---

src/provider-guides/aweber.mdx
src/provider-guides/ringCentral.mdx
src/provider-guides/slack.mdx

fix: issues with Slack, AWeber and RingCentral guides

---

src/provider-guides/breakcold.mdx

[CON-2065] feat: [breakcold] Extended the provider guides

---

src/provider-guides/blackbaud.mdx

[CON-2085] feat: [blackbaud] Extended the provider guides.

---

src/embeddable-ui-components.mdx

fix: typos in embed UI components page

---

src/provider-guides/hubspot.mdx

Update casing in Hubspot provider guide

---

src/provider-guides/hubspot.mdx

Update HubSpot guide with required scope for user sync

---

src/provider-guides/mixmax.mdx

Adds supported objects y read and write connector

[CON-1458] feat: extend mixmax connector documentation

---

src/provider-guides/asana.mdx

This PR add missing write objects.

fix (Asana): add missing write objects.

---

src/provider-guides/gong.mdx

gong: Add Flows read object

---

src/docs.json
src/generate-docs.ts
src/provider-guides/chorus.mdx

[CON-2166] feat: [chorus] Added the provider guide.

---

src/docs.json
src/generate-docs.ts
src/provider-guides/amplitude.mdx

This PR adds provider guide for Amplitude proxy + Deep connector

[CON-2251] feat: add Amplitude provider guide
